### ISSUE TITLE
Can't execute more than one command at a time

### ISSUE THREAD

**Issue by a-santo** [elespike/hubot-no-js#2]
Hi,

Thanks for effort implementing this. 

I've noticed that it seems to not be possible to execute more than one command at a time. If I run a command that executes a python script that takes a few seconds/minutes to complete, all other commands that are sent while the first script is running are ignored. Is there a way to get around this apparent limitation or am I just missing something?

Thanks!

**Comment by elespike** [comment]
Hi, @a-santo!

Thanks for reaching out. I've already dealt away with this self-imposed limitation within the dev branch. But the dev branch isn't usable yet, so I've highlighted the necessary changes for you here:

https://github.com/elespike/hubot-no-js/commit/0427be14df8f01cc5dab5a29cf4be1be9a70f8f1

That should do the trick. =)

**Comment by a-santo** [comment]
Thanks, @elespike 

That does the trick indeed 👍

**Comment by elespike** [comment]
Excellent!

The dev branch will be ready soon, so keep an eye out. =)
